spring.application.name=CineFlow_Cartelera
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/cartelera?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# RabbitMQ (Event Bus)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.events.exchange=cineflow.events.exchange
app.events.ticket-paid.routing-key=ticket.paid
app.events.ticket-paid.cartelera-queue=ticket.paid.cartelera.queue
app.events.ticket-reserved.routing-key=ticket.reserved
app.events.ticket-reserved.cartelera-queue=ticket.reserved.cartelera.queue
